from type_constants import SubAdmissionTypes

condition_age_probability_dict = {

    SubAdmissionTypes.CANCER.name: {
        'Bladder Cancer': [],
        'Brain and Nervous System Cancers': [],
        'Breast Cancer': [],
        'Cervical Cancer': [],
        'Colorectal Cancer': [],
        'Endometrial (Uterine) Cancer': [],
        'Esophageal Cancer': [],
        'Head and Neck Cancers': [],
        'Kidney (Renal) Cancer': [],
        'Leukemia': [],
        'Liver Cancer': [],
        'Lung Cancer': [],
        'Melanoma of Skin': [],
        'Non-Hodgkin Lymphoma': [],
        'Ovarian Cancer': [],
        'Pancreatic Cancer': [],
        'Prostate Cancer': [],
        'Stomach (Gastric) Cancer': [],
        'Testicular Cancer': [],
        'Thyroid Cancer': []},
    SubAdmissionTypes.CARDIOLOGY.name: {
        'Aneurysms': [],
        'Arrhythmias': [],
        'Coronary Artery Disease': [],
        'Heart Attack': [],
        'Heart Failure': [],
        'Hypertension (High Blood Pressure)': [],
        'Peripheral Artery Disease': [],
        'Stroke': [],
        'Venous Thromboembolism': []},
    SubAdmissionTypes.DERMATOLOGY.name: {
        'Acne': [],
        'Cellulitis': [],
        'Dermatitis': [],
        'Eczema': [],
        'Hives (Urticaria)': [],
        'Impetigo': [],
        'Psoriasis': [],
        'Rosacea': [],
        'Shingles (Herpes Zoster)': [],
        'Skin Cancer': []},
    SubAdmissionTypes.ENDOCRINOLOGY.name: {
        "Addison's Disease": [],
        "Cushing's Syndrome": [],
        'Diabetes Mellitus - Type 1 and Type 2': [],
        'Gout': [],
        'Hyperlipidaemia': [],
        'Metabolic Syndrome': [],
        'Osteoporosis': [],
        'Pituitary Disorders': [],
        'Polycystic Ovary Syndrome (PCOS)': [],
        'Thyroid Disorders - including Hypothyroidism and Hyperthyroidism': []},
    SubAdmissionTypes.GASTROENTEROLOGY.name: {
        'Chronic Liver Disease - including Hepatitis and Cirrhosis': [],
        'Coeliac Disease': [],
        'Diverticular Disease': [],
        'Gallstones': [],
        'Gastro-oesophageal Reflux Disease (GORD)': [],
        'Gastroenteritis': [],
        "Inflammatory Bowel Disease (IBD) - including Crohn's Disease and Ulcerative Colitis": [],
        'Irritable Bowel Syndrome (IBS)': [],
        'Pancreatitis': [],
        'Peptic Ulcers': []},
    SubAdmissionTypes.GASTROINTESTINAL_DISORDERS.name: {
        'Celiac Disease': [],
        'Cirrhosis': [],
        "Crohn's Disease": [],
        'Gallstones': [],
        'Gastroesophageal Reflux Disease (GERD)': [],
        'Hepatitis': [],
        'Irritable Bowel Syndrome (IBS)': [],
        'Pancreatitis': [],
        'Peptic Ulcer Disease': [],
        'Ulcerative Colitis': []},
    SubAdmissionTypes.GERIATRICS.name: {

    },
    SubAdmissionTypes.HEMATOLOGY.name: {
        'Anemia': [],
        'Deep Vein Thrombosis (DVT)': [],
        'Hemochromatosis': [],
        'Hemophilia': [],
        'Iron Deficiency Anemia': [],
        'Leukemia': [],
        'Lymphoma': [],
        'Polycythemia Vera': [],
        'Sickle Cell Disease': [],
        'Thrombocytopenia': []},
    SubAdmissionTypes.INFECTIOUS_DISEASES.name: {
        'COVID-19': [],
        'HIV/AIDS': [],
        'Hepatitis': [],
        'Herpes Simplex Virus': [],
        'Influenza': [],
        'Malaria': [],
        'Strep Throat': [],
        'Tuberculosis': [],
        'Urinary Tract Infections (UTIs)': []},
    SubAdmissionTypes.INJURY_RTC.name: {
        'Abrasions': [],
        'Acoustic Trauma': [],
        'Airbag Injuries': [],
        'Amputations': [],
        'Burn Injuries': [],
        'Bursitis': [],
        'Cervical Spine Injuries': [],
        'Compartment Syndrome': [],
        'Concussions': [],
        'Contusions (bruises)': [],
        'Crush Injuries': [],
        'Dental Injuries': [],
        'Dislocations': [],
        'Drowning or Near-Drowning Incidents': [],
        'Eye Injuries': [],
        'Facial Fractures': [],
        'Fractures': [],
        'Heatstroke': [],
        'Hematomas': [],
        'Hypothermia or Frostbite': [],
        'Internal Bleeding': [],
        'Lacerations': [],
        'Lower Extremity Injuries': [],
        'Lumbar Spine Injuries': [],
        'Nerve Damage': [],
        'Organ Damage': [],
        'Pelvic Fractures': [],
        'Pneumothorax (collapsed lung)': [],
        'Post-Traumatic Arthritis': [],
        'Psychological Trauma': [],
        'Rib Fractures': [],
        'Seat Belt Injuries': [],
        'Skull Fractures': [],
        'Soft Tissue Injuries': [],
        'Spinal Cord Injuries': [],
        'Sprains': [],
        'Strains': [],
        'Stress Fractures': [],
        'Tendon Injuries': [],
        'Thoracic Spine Injuries': [],
        'Traumatic Brain Injuries (TBIs)': [],
        'Upper Extremity Injuries': [],
        'Whiplash': []},
    SubAdmissionTypes.MATERNITY.name: {
        'Antepartum Haemorrhage': [],
        'Gestational Diabetes Monitoring': [],
        'Induction of Labour': [],
        'Labour and Delivery': [],
        'Postpartum Complications': [],
        'Pre-eclampsia/Eclampsia': [],
        'Pregnancy-induced Hypertension': [],
        'Preterm Labour': [],
        'Ruptured Membranes without Contractions': [],
        'Scheduled Caesarean Section': []},
    SubAdmissionTypes.MUSCULOSKELETAL.name: {
        'Ankylosing Spondylitis': [],
        'Bursitis': [],
        'Fibromyalgia': [],
        'Gout': [],
        'Low Back Pain': [],
        'Lupus': [],
        'Plantar Fasciitis': [],
        'Polymyalgia Rheumatica': [],
        'Repetitive Strain Injury (RSI)': [],
        'Tendinitis': []},
    SubAdmissionTypes.NEPHROLOGY.name: {
        'Acute Kidney Injury (AKI)': [],
        'Chronic Kidney Disease (CKD)': [],
        'Glomerulonephritis': [],
        'Haemodialysis-related Amyloidosis': [],
        'Hyperkalaemia': [],
        'Nephrotic Syndrome': [],
        'Renal Artery Stenosis': [],
        "Polycystic Kidney Disease": [((0, 18), 0.0001)],
        "Kidney Stones": [((0, 5), 0.0002), ((5, 18), 0.001)],
        "Urinary Tract Infections (UTIs)": [((0, 5), 0.0001), ((5, 11), 0.0002), ((11, 13), 0.001)],
    },
    SubAdmissionTypes.NEUROLOGY.name: {
        "Alzheimer's Disease": [],
        "Bell's Palsy": [],
        'Concussion': [],
        'Epilepsy': [],
        'Migraines': [],
        'Multiple Sclerosis': [],
        "Parkinson's Disease": [],
        'Peripheral Neuropathy': [],
        'Sciatica': [],
        'Stroke': []},
    SubAdmissionTypes.OBSTETRICS.name: {
        'Breast Disorders': [],
        'Congenital Reproductive Anomalies': [],
        'Endometriosis': [],
        'Gynecological Tumors': [],
        'Menstrual Disorders': [],
        'Polycystic Ovary Syndrome (PCOS)': [],
        'Precocious Puberty': [],
        'Premature Ovarian Insufficiency (POI)': [],
        'Turner Syndrome': [],
        'Vulvovaginitis': []},
    SubAdmissionTypes.ONCOLOGY.name: {
        'Bladder Cancer': [],
        'Breast Cancer': [],
        'Colorectal Cancer': [],
        'Leukemia': [],
        'Lung Cancer': [],
        'Lymphoma': [],
        'Melanoma': [],
        'Ovarian Cancer': [],
        'Pancreatic Cancer': [],
        'Prostate Cancer': []},
    SubAdmissionTypes.OPHTHALMOLOGY.name: {
        'Age-related Macular Degeneration (AMD)': [],
        'Cataracts': [],
        'Conjunctivitis': [],
        'Diabetic Retinopathy': [],
        'Dry Eye Syndrome': [],
        'Glaucoma': [],
        'Keratitis': [],
        'Refractive Errors': [],
        'Retinal Detachment': [],
        'Uveitis': []},
    SubAdmissionTypes.ORTHOPEDICS.name: {
        'Anterior Cruciate Ligament (ACL) Injuries': [],
        'Carpal Tunnel Syndrome': [],
        'Fractures': [],
        'Meniscus Tears': [],
        'Osteoarthritis': [],
        'Osteoporosis': [],
        'Rheumatoid Arthritis': [],
        'Rotator Cuff Tears': [],
        'Scoliosis': [],
        'Spinal Disc Herniation': []},
    SubAdmissionTypes.OTORHINOLARYNGOLOGY_ENT.name: {
        'Hearing Loss': [],
        'Laryngitis': [],
        "Meniere's Disease": [],
        "Otitis Externa (Swimmer's Ear)": [],
        'Otitis Media (Middle Ear Infection)': [],
        'Pharyngitis': [],
        'Rhinitis': [],
        'Sinusitis': [],
        'Tinnitus': [],
        'Tonsillitis': []},
    SubAdmissionTypes.PSYCHIATRIC.name: {
        'Anxiety Disorders': [],
        'Attention Deficit Hyperactivity Disorder (ADHD)': [],
        'Autism Spectrum Disorder': [],
        'Bipolar Disorder': [],
        'Depression': [],
        'Eating Disorders (Anorexia, Bulimia)': [],
        'Insomnia': [],
        'Obsessive-Compulsive Disorder (OCD)': [],
        'Post-Traumatic Stress Disorder (PTSD)': [],
        'Schizophrenia': []},
    SubAdmissionTypes.RESPIRATORY.name: {
        'Allergic Rhinitis': [],
        'Asthma': [],
        'Bronchitis': [],
        'Chronic Obstructive Pulmonary Disease (COPD)': [],
        'Cystic Fibrosis': [],
        'Lung Cancer': [],
        'Pneumonia': [],
        'Pulmonary Embolism': [],
        'Sinusitis': [],
        'Sleep Apnea': []},
    SubAdmissionTypes.SELF_INFLICTED.name: {
        'Bone breaking': [],
        'Burning': [],
        'Hair pulling (Trichotillomania)': [],
        'Head banging': [],
        'Ingesting harmful substances': [],
        'Lacerations or cuts': [],
        'Overdose': [],
        'Piercing the skin': [],
        'Self-hitting': [],
        'Skin picking (Dermatillomania)': []}
}

#
# if __name__ == "__main__":
#     conditions_age_probability = {}
#     for sub, cd in zip(SubAdmissionTypes, ConditionsOrDiagnosis):
#         conditions_dict = {
#
#         }
#         for condition in cd.value:
#             conditions_dict[condition] = []
#
#         conditions_age_probability[f"SubAdmissionTypes.{sub}.name"] = conditions_dict
#     pprint(conditions_age_probability)
